/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2018-7-28")
public class ContextServiceInput implements org.apache.thrift.TBase<ContextServiceInput, ContextServiceInput._Fields>, java.io.Serializable, Cloneable, Comparable<ContextServiceInput> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ContextServiceInput");

  private static final org.apache.thrift.protocol.TField LAST_QUERY_FIELD_DESC = new org.apache.thrift.protocol.TField("last_query", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField LAST_REPLY_FIELD_DESC = new org.apache.thrift.protocol.TField("last_reply", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField LAST_QUERY_BASIC_SEG_FIELD_DESC = new org.apache.thrift.protocol.TField("last_query_basic_seg", org.apache.thrift.protocol.TType.LIST, (short)21);
  private static final org.apache.thrift.protocol.TField LAST_QUERY_PHRASE_SEG_FIELD_DESC = new org.apache.thrift.protocol.TField("last_query_phrase_seg", org.apache.thrift.protocol.TType.LIST, (short)22);
  private static final org.apache.thrift.protocol.TField LAST_REPLY_BASIC_SEG_FIELD_DESC = new org.apache.thrift.protocol.TField("last_reply_basic_seg", org.apache.thrift.protocol.TType.LIST, (short)23);
  private static final org.apache.thrift.protocol.TField LAST_REPLY_PHRASE_SEG_FIELD_DESC = new org.apache.thrift.protocol.TField("last_reply_phrase_seg", org.apache.thrift.protocol.TType.LIST, (short)24);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ContextServiceInputStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ContextServiceInputTupleSchemeFactory());
  }

  public String last_query; // optional
  public String last_reply; // optional
  public List<String> last_query_basic_seg; // optional
  public List<String> last_query_phrase_seg; // optional
  public List<String> last_reply_basic_seg; // optional
  public List<String> last_reply_phrase_seg; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LAST_QUERY((short)1, "last_query"),
    LAST_REPLY((short)2, "last_reply"),
    LAST_QUERY_BASIC_SEG((short)21, "last_query_basic_seg"),
    LAST_QUERY_PHRASE_SEG((short)22, "last_query_phrase_seg"),
    LAST_REPLY_BASIC_SEG((short)23, "last_reply_basic_seg"),
    LAST_REPLY_PHRASE_SEG((short)24, "last_reply_phrase_seg");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LAST_QUERY
          return LAST_QUERY;
        case 2: // LAST_REPLY
          return LAST_REPLY;
        case 21: // LAST_QUERY_BASIC_SEG
          return LAST_QUERY_BASIC_SEG;
        case 22: // LAST_QUERY_PHRASE_SEG
          return LAST_QUERY_PHRASE_SEG;
        case 23: // LAST_REPLY_BASIC_SEG
          return LAST_REPLY_BASIC_SEG;
        case 24: // LAST_REPLY_PHRASE_SEG
          return LAST_REPLY_PHRASE_SEG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.LAST_QUERY,_Fields.LAST_REPLY,_Fields.LAST_QUERY_BASIC_SEG,_Fields.LAST_QUERY_PHRASE_SEG,_Fields.LAST_REPLY_BASIC_SEG,_Fields.LAST_REPLY_PHRASE_SEG};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LAST_QUERY, new org.apache.thrift.meta_data.FieldMetaData("last_query", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAST_REPLY, new org.apache.thrift.meta_data.FieldMetaData("last_reply", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAST_QUERY_BASIC_SEG, new org.apache.thrift.meta_data.FieldMetaData("last_query_basic_seg", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.LAST_QUERY_PHRASE_SEG, new org.apache.thrift.meta_data.FieldMetaData("last_query_phrase_seg", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.LAST_REPLY_BASIC_SEG, new org.apache.thrift.meta_data.FieldMetaData("last_reply_basic_seg", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.LAST_REPLY_PHRASE_SEG, new org.apache.thrift.meta_data.FieldMetaData("last_reply_phrase_seg", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ContextServiceInput.class, metaDataMap);
  }

  public ContextServiceInput() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ContextServiceInput(ContextServiceInput other) {
    if (other.isSetLast_query()) {
      this.last_query = other.last_query;
    }
    if (other.isSetLast_reply()) {
      this.last_reply = other.last_reply;
    }
    if (other.isSetLast_query_basic_seg()) {
      List<String> __this__last_query_basic_seg = new ArrayList<String>(other.last_query_basic_seg);
      this.last_query_basic_seg = __this__last_query_basic_seg;
    }
    if (other.isSetLast_query_phrase_seg()) {
      List<String> __this__last_query_phrase_seg = new ArrayList<String>(other.last_query_phrase_seg);
      this.last_query_phrase_seg = __this__last_query_phrase_seg;
    }
    if (other.isSetLast_reply_basic_seg()) {
      List<String> __this__last_reply_basic_seg = new ArrayList<String>(other.last_reply_basic_seg);
      this.last_reply_basic_seg = __this__last_reply_basic_seg;
    }
    if (other.isSetLast_reply_phrase_seg()) {
      List<String> __this__last_reply_phrase_seg = new ArrayList<String>(other.last_reply_phrase_seg);
      this.last_reply_phrase_seg = __this__last_reply_phrase_seg;
    }
  }

  public ContextServiceInput deepCopy() {
    return new ContextServiceInput(this);
  }

  
  public void clear() {
    this.last_query = null;
    this.last_reply = null;
    this.last_query_basic_seg = null;
    this.last_query_phrase_seg = null;
    this.last_reply_basic_seg = null;
    this.last_reply_phrase_seg = null;
  }

  public String getLast_query() {
    return this.last_query;
  }

  public ContextServiceInput setLast_query(String last_query) {
    this.last_query = last_query;
    return this;
  }

  public void unsetLast_query() {
    this.last_query = null;
  }

  /** Returns true if field last_query is set (has been assigned a value) and false otherwise */
  public boolean isSetLast_query() {
    return this.last_query != null;
  }

  public void setLast_queryIsSet(boolean value) {
    if (!value) {
      this.last_query = null;
    }
  }

  public String getLast_reply() {
    return this.last_reply;
  }

  public ContextServiceInput setLast_reply(String last_reply) {
    this.last_reply = last_reply;
    return this;
  }

  public void unsetLast_reply() {
    this.last_reply = null;
  }

  /** Returns true if field last_reply is set (has been assigned a value) and false otherwise */
  public boolean isSetLast_reply() {
    return this.last_reply != null;
  }

  public void setLast_replyIsSet(boolean value) {
    if (!value) {
      this.last_reply = null;
    }
  }

  public int getLast_query_basic_segSize() {
    return (this.last_query_basic_seg == null) ? 0 : this.last_query_basic_seg.size();
  }

  public java.util.Iterator<String> getLast_query_basic_segIterator() {
    return (this.last_query_basic_seg == null) ? null : this.last_query_basic_seg.iterator();
  }

  public void addToLast_query_basic_seg(String elem) {
    if (this.last_query_basic_seg == null) {
      this.last_query_basic_seg = new ArrayList<String>();
    }
    this.last_query_basic_seg.add(elem);
  }

  public List<String> getLast_query_basic_seg() {
    return this.last_query_basic_seg;
  }

  public ContextServiceInput setLast_query_basic_seg(List<String> last_query_basic_seg) {
    this.last_query_basic_seg = last_query_basic_seg;
    return this;
  }

  public void unsetLast_query_basic_seg() {
    this.last_query_basic_seg = null;
  }

  /** Returns true if field last_query_basic_seg is set (has been assigned a value) and false otherwise */
  public boolean isSetLast_query_basic_seg() {
    return this.last_query_basic_seg != null;
  }

  public void setLast_query_basic_segIsSet(boolean value) {
    if (!value) {
      this.last_query_basic_seg = null;
    }
  }

  public int getLast_query_phrase_segSize() {
    return (this.last_query_phrase_seg == null) ? 0 : this.last_query_phrase_seg.size();
  }

  public java.util.Iterator<String> getLast_query_phrase_segIterator() {
    return (this.last_query_phrase_seg == null) ? null : this.last_query_phrase_seg.iterator();
  }

  public void addToLast_query_phrase_seg(String elem) {
    if (this.last_query_phrase_seg == null) {
      this.last_query_phrase_seg = new ArrayList<String>();
    }
    this.last_query_phrase_seg.add(elem);
  }

  public List<String> getLast_query_phrase_seg() {
    return this.last_query_phrase_seg;
  }

  public ContextServiceInput setLast_query_phrase_seg(List<String> last_query_phrase_seg) {
    this.last_query_phrase_seg = last_query_phrase_seg;
    return this;
  }

  public void unsetLast_query_phrase_seg() {
    this.last_query_phrase_seg = null;
  }

  /** Returns true if field last_query_phrase_seg is set (has been assigned a value) and false otherwise */
  public boolean isSetLast_query_phrase_seg() {
    return this.last_query_phrase_seg != null;
  }

  public void setLast_query_phrase_segIsSet(boolean value) {
    if (!value) {
      this.last_query_phrase_seg = null;
    }
  }

  public int getLast_reply_basic_segSize() {
    return (this.last_reply_basic_seg == null) ? 0 : this.last_reply_basic_seg.size();
  }

  public java.util.Iterator<String> getLast_reply_basic_segIterator() {
    return (this.last_reply_basic_seg == null) ? null : this.last_reply_basic_seg.iterator();
  }

  public void addToLast_reply_basic_seg(String elem) {
    if (this.last_reply_basic_seg == null) {
      this.last_reply_basic_seg = new ArrayList<String>();
    }
    this.last_reply_basic_seg.add(elem);
  }

  public List<String> getLast_reply_basic_seg() {
    return this.last_reply_basic_seg;
  }

  public ContextServiceInput setLast_reply_basic_seg(List<String> last_reply_basic_seg) {
    this.last_reply_basic_seg = last_reply_basic_seg;
    return this;
  }

  public void unsetLast_reply_basic_seg() {
    this.last_reply_basic_seg = null;
  }

  /** Returns true if field last_reply_basic_seg is set (has been assigned a value) and false otherwise */
  public boolean isSetLast_reply_basic_seg() {
    return this.last_reply_basic_seg != null;
  }

  public void setLast_reply_basic_segIsSet(boolean value) {
    if (!value) {
      this.last_reply_basic_seg = null;
    }
  }

  public int getLast_reply_phrase_segSize() {
    return (this.last_reply_phrase_seg == null) ? 0 : this.last_reply_phrase_seg.size();
  }

  public java.util.Iterator<String> getLast_reply_phrase_segIterator() {
    return (this.last_reply_phrase_seg == null) ? null : this.last_reply_phrase_seg.iterator();
  }

  public void addToLast_reply_phrase_seg(String elem) {
    if (this.last_reply_phrase_seg == null) {
      this.last_reply_phrase_seg = new ArrayList<String>();
    }
    this.last_reply_phrase_seg.add(elem);
  }

  public List<String> getLast_reply_phrase_seg() {
    return this.last_reply_phrase_seg;
  }

  public ContextServiceInput setLast_reply_phrase_seg(List<String> last_reply_phrase_seg) {
    this.last_reply_phrase_seg = last_reply_phrase_seg;
    return this;
  }

  public void unsetLast_reply_phrase_seg() {
    this.last_reply_phrase_seg = null;
  }

  /** Returns true if field last_reply_phrase_seg is set (has been assigned a value) and false otherwise */
  public boolean isSetLast_reply_phrase_seg() {
    return this.last_reply_phrase_seg != null;
  }

  public void setLast_reply_phrase_segIsSet(boolean value) {
    if (!value) {
      this.last_reply_phrase_seg = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LAST_QUERY:
      if (value == null) {
        unsetLast_query();
      } else {
        setLast_query((String)value);
      }
      break;

    case LAST_REPLY:
      if (value == null) {
        unsetLast_reply();
      } else {
        setLast_reply((String)value);
      }
      break;

    case LAST_QUERY_BASIC_SEG:
      if (value == null) {
        unsetLast_query_basic_seg();
      } else {
        setLast_query_basic_seg((List<String>)value);
      }
      break;

    case LAST_QUERY_PHRASE_SEG:
      if (value == null) {
        unsetLast_query_phrase_seg();
      } else {
        setLast_query_phrase_seg((List<String>)value);
      }
      break;

    case LAST_REPLY_BASIC_SEG:
      if (value == null) {
        unsetLast_reply_basic_seg();
      } else {
        setLast_reply_basic_seg((List<String>)value);
      }
      break;

    case LAST_REPLY_PHRASE_SEG:
      if (value == null) {
        unsetLast_reply_phrase_seg();
      } else {
        setLast_reply_phrase_seg((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LAST_QUERY:
      return getLast_query();

    case LAST_REPLY:
      return getLast_reply();

    case LAST_QUERY_BASIC_SEG:
      return getLast_query_basic_seg();

    case LAST_QUERY_PHRASE_SEG:
      return getLast_query_phrase_seg();

    case LAST_REPLY_BASIC_SEG:
      return getLast_reply_basic_seg();

    case LAST_REPLY_PHRASE_SEG:
      return getLast_reply_phrase_seg();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LAST_QUERY:
      return isSetLast_query();
    case LAST_REPLY:
      return isSetLast_reply();
    case LAST_QUERY_BASIC_SEG:
      return isSetLast_query_basic_seg();
    case LAST_QUERY_PHRASE_SEG:
      return isSetLast_query_phrase_seg();
    case LAST_REPLY_BASIC_SEG:
      return isSetLast_reply_basic_seg();
    case LAST_REPLY_PHRASE_SEG:
      return isSetLast_reply_phrase_seg();
    }
    throw new IllegalStateException();
  }

  
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ContextServiceInput)
      return this.equals((ContextServiceInput)that);
    return false;
  }

  public boolean equals(ContextServiceInput that) {
    if (that == null)
      return false;

    boolean this_present_last_query = true && this.isSetLast_query();
    boolean that_present_last_query = true && that.isSetLast_query();
    if (this_present_last_query || that_present_last_query) {
      if (!(this_present_last_query && that_present_last_query))
        return false;
      if (!this.last_query.equals(that.last_query))
        return false;
    }

    boolean this_present_last_reply = true && this.isSetLast_reply();
    boolean that_present_last_reply = true && that.isSetLast_reply();
    if (this_present_last_reply || that_present_last_reply) {
      if (!(this_present_last_reply && that_present_last_reply))
        return false;
      if (!this.last_reply.equals(that.last_reply))
        return false;
    }

    boolean this_present_last_query_basic_seg = true && this.isSetLast_query_basic_seg();
    boolean that_present_last_query_basic_seg = true && that.isSetLast_query_basic_seg();
    if (this_present_last_query_basic_seg || that_present_last_query_basic_seg) {
      if (!(this_present_last_query_basic_seg && that_present_last_query_basic_seg))
        return false;
      if (!this.last_query_basic_seg.equals(that.last_query_basic_seg))
        return false;
    }

    boolean this_present_last_query_phrase_seg = true && this.isSetLast_query_phrase_seg();
    boolean that_present_last_query_phrase_seg = true && that.isSetLast_query_phrase_seg();
    if (this_present_last_query_phrase_seg || that_present_last_query_phrase_seg) {
      if (!(this_present_last_query_phrase_seg && that_present_last_query_phrase_seg))
        return false;
      if (!this.last_query_phrase_seg.equals(that.last_query_phrase_seg))
        return false;
    }

    boolean this_present_last_reply_basic_seg = true && this.isSetLast_reply_basic_seg();
    boolean that_present_last_reply_basic_seg = true && that.isSetLast_reply_basic_seg();
    if (this_present_last_reply_basic_seg || that_present_last_reply_basic_seg) {
      if (!(this_present_last_reply_basic_seg && that_present_last_reply_basic_seg))
        return false;
      if (!this.last_reply_basic_seg.equals(that.last_reply_basic_seg))
        return false;
    }

    boolean this_present_last_reply_phrase_seg = true && this.isSetLast_reply_phrase_seg();
    boolean that_present_last_reply_phrase_seg = true && that.isSetLast_reply_phrase_seg();
    if (this_present_last_reply_phrase_seg || that_present_last_reply_phrase_seg) {
      if (!(this_present_last_reply_phrase_seg && that_present_last_reply_phrase_seg))
        return false;
      if (!this.last_reply_phrase_seg.equals(that.last_reply_phrase_seg))
        return false;
    }

    return true;
  }

  
  public int hashCode() {
    return 0;
  }

  
  public int compareTo(ContextServiceInput other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLast_query()).compareTo(other.isSetLast_query());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLast_query()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.last_query, other.last_query);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLast_reply()).compareTo(other.isSetLast_reply());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLast_reply()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.last_reply, other.last_reply);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLast_query_basic_seg()).compareTo(other.isSetLast_query_basic_seg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLast_query_basic_seg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.last_query_basic_seg, other.last_query_basic_seg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLast_query_phrase_seg()).compareTo(other.isSetLast_query_phrase_seg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLast_query_phrase_seg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.last_query_phrase_seg, other.last_query_phrase_seg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLast_reply_basic_seg()).compareTo(other.isSetLast_reply_basic_seg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLast_reply_basic_seg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.last_reply_basic_seg, other.last_reply_basic_seg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLast_reply_phrase_seg()).compareTo(other.isSetLast_reply_phrase_seg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLast_reply_phrase_seg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.last_reply_phrase_seg, other.last_reply_phrase_seg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  
  public String toString() {
    StringBuilder sb = new StringBuilder("ContextServiceInput(");
    boolean first = true;

    if (isSetLast_query()) {
      sb.append("last_query:");
      if (this.last_query == null) {
        sb.append("null");
      } else {
        sb.append(this.last_query);
      }
      first = false;
    }
    if (isSetLast_reply()) {
      if (!first) sb.append(", ");
      sb.append("last_reply:");
      if (this.last_reply == null) {
        sb.append("null");
      } else {
        sb.append(this.last_reply);
      }
      first = false;
    }
    if (isSetLast_query_basic_seg()) {
      if (!first) sb.append(", ");
      sb.append("last_query_basic_seg:");
      if (this.last_query_basic_seg == null) {
        sb.append("null");
      } else {
        sb.append(this.last_query_basic_seg);
      }
      first = false;
    }
    if (isSetLast_query_phrase_seg()) {
      if (!first) sb.append(", ");
      sb.append("last_query_phrase_seg:");
      if (this.last_query_phrase_seg == null) {
        sb.append("null");
      } else {
        sb.append(this.last_query_phrase_seg);
      }
      first = false;
    }
    if (isSetLast_reply_basic_seg()) {
      if (!first) sb.append(", ");
      sb.append("last_reply_basic_seg:");
      if (this.last_reply_basic_seg == null) {
        sb.append("null");
      } else {
        sb.append(this.last_reply_basic_seg);
      }
      first = false;
    }
    if (isSetLast_reply_phrase_seg()) {
      if (!first) sb.append(", ");
      sb.append("last_reply_phrase_seg:");
      if (this.last_reply_phrase_seg == null) {
        sb.append("null");
      } else {
        sb.append(this.last_reply_phrase_seg);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ContextServiceInputStandardSchemeFactory implements SchemeFactory {
    public ContextServiceInputStandardScheme getScheme() {
      return new ContextServiceInputStandardScheme();
    }
  }

  private static class ContextServiceInputStandardScheme extends StandardScheme<ContextServiceInput> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ContextServiceInput struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LAST_QUERY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.last_query = iprot.readString();
              struct.setLast_queryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LAST_REPLY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.last_reply = iprot.readString();
              struct.setLast_replyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 21: // LAST_QUERY_BASIC_SEG
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list458 = iprot.readListBegin();
                struct.last_query_basic_seg = new ArrayList<String>(_list458.size);
                for (int _i459 = 0; _i459 < _list458.size; ++_i459)
                {
                  String _elem460;
                  _elem460 = iprot.readString();
                  struct.last_query_basic_seg.add(_elem460);
                }
                iprot.readListEnd();
              }
              struct.setLast_query_basic_segIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 22: // LAST_QUERY_PHRASE_SEG
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list461 = iprot.readListBegin();
                struct.last_query_phrase_seg = new ArrayList<String>(_list461.size);
                for (int _i462 = 0; _i462 < _list461.size; ++_i462)
                {
                  String _elem463;
                  _elem463 = iprot.readString();
                  struct.last_query_phrase_seg.add(_elem463);
                }
                iprot.readListEnd();
              }
              struct.setLast_query_phrase_segIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 23: // LAST_REPLY_BASIC_SEG
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list464 = iprot.readListBegin();
                struct.last_reply_basic_seg = new ArrayList<String>(_list464.size);
                for (int _i465 = 0; _i465 < _list464.size; ++_i465)
                {
                  String _elem466;
                  _elem466 = iprot.readString();
                  struct.last_reply_basic_seg.add(_elem466);
                }
                iprot.readListEnd();
              }
              struct.setLast_reply_basic_segIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 24: // LAST_REPLY_PHRASE_SEG
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list467 = iprot.readListBegin();
                struct.last_reply_phrase_seg = new ArrayList<String>(_list467.size);
                for (int _i468 = 0; _i468 < _list467.size; ++_i468)
                {
                  String _elem469;
                  _elem469 = iprot.readString();
                  struct.last_reply_phrase_seg.add(_elem469);
                }
                iprot.readListEnd();
              }
              struct.setLast_reply_phrase_segIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ContextServiceInput struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.last_query != null) {
        if (struct.isSetLast_query()) {
          oprot.writeFieldBegin(LAST_QUERY_FIELD_DESC);
          oprot.writeString(struct.last_query);
          oprot.writeFieldEnd();
        }
      }
      if (struct.last_reply != null) {
        if (struct.isSetLast_reply()) {
          oprot.writeFieldBegin(LAST_REPLY_FIELD_DESC);
          oprot.writeString(struct.last_reply);
          oprot.writeFieldEnd();
        }
      }
      if (struct.last_query_basic_seg != null) {
        if (struct.isSetLast_query_basic_seg()) {
          oprot.writeFieldBegin(LAST_QUERY_BASIC_SEG_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.last_query_basic_seg.size()));
            for (String _iter470 : struct.last_query_basic_seg)
            {
              oprot.writeString(_iter470);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.last_query_phrase_seg != null) {
        if (struct.isSetLast_query_phrase_seg()) {
          oprot.writeFieldBegin(LAST_QUERY_PHRASE_SEG_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.last_query_phrase_seg.size()));
            for (String _iter471 : struct.last_query_phrase_seg)
            {
              oprot.writeString(_iter471);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.last_reply_basic_seg != null) {
        if (struct.isSetLast_reply_basic_seg()) {
          oprot.writeFieldBegin(LAST_REPLY_BASIC_SEG_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.last_reply_basic_seg.size()));
            for (String _iter472 : struct.last_reply_basic_seg)
            {
              oprot.writeString(_iter472);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.last_reply_phrase_seg != null) {
        if (struct.isSetLast_reply_phrase_seg()) {
          oprot.writeFieldBegin(LAST_REPLY_PHRASE_SEG_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.last_reply_phrase_seg.size()));
            for (String _iter473 : struct.last_reply_phrase_seg)
            {
              oprot.writeString(_iter473);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ContextServiceInputTupleSchemeFactory implements SchemeFactory {
    public ContextServiceInputTupleScheme getScheme() {
      return new ContextServiceInputTupleScheme();
    }
  }

  private static class ContextServiceInputTupleScheme extends TupleScheme<ContextServiceInput> {

    
    public void write(org.apache.thrift.protocol.TProtocol prot, ContextServiceInput struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLast_query()) {
        optionals.set(0);
      }
      if (struct.isSetLast_reply()) {
        optionals.set(1);
      }
      if (struct.isSetLast_query_basic_seg()) {
        optionals.set(2);
      }
      if (struct.isSetLast_query_phrase_seg()) {
        optionals.set(3);
      }
      if (struct.isSetLast_reply_basic_seg()) {
        optionals.set(4);
      }
      if (struct.isSetLast_reply_phrase_seg()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetLast_query()) {
        oprot.writeString(struct.last_query);
      }
      if (struct.isSetLast_reply()) {
        oprot.writeString(struct.last_reply);
      }
      if (struct.isSetLast_query_basic_seg()) {
        {
          oprot.writeI32(struct.last_query_basic_seg.size());
          for (String _iter474 : struct.last_query_basic_seg)
          {
            oprot.writeString(_iter474);
          }
        }
      }
      if (struct.isSetLast_query_phrase_seg()) {
        {
          oprot.writeI32(struct.last_query_phrase_seg.size());
          for (String _iter475 : struct.last_query_phrase_seg)
          {
            oprot.writeString(_iter475);
          }
        }
      }
      if (struct.isSetLast_reply_basic_seg()) {
        {
          oprot.writeI32(struct.last_reply_basic_seg.size());
          for (String _iter476 : struct.last_reply_basic_seg)
          {
            oprot.writeString(_iter476);
          }
        }
      }
      if (struct.isSetLast_reply_phrase_seg()) {
        {
          oprot.writeI32(struct.last_reply_phrase_seg.size());
          for (String _iter477 : struct.last_reply_phrase_seg)
          {
            oprot.writeString(_iter477);
          }
        }
      }
    }

    
    public void read(org.apache.thrift.protocol.TProtocol prot, ContextServiceInput struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.last_query = iprot.readString();
        struct.setLast_queryIsSet(true);
      }
      if (incoming.get(1)) {
        struct.last_reply = iprot.readString();
        struct.setLast_replyIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list478 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.last_query_basic_seg = new ArrayList<String>(_list478.size);
          for (int _i479 = 0; _i479 < _list478.size; ++_i479)
          {
            String _elem480;
            _elem480 = iprot.readString();
            struct.last_query_basic_seg.add(_elem480);
          }
        }
        struct.setLast_query_basic_segIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list481 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.last_query_phrase_seg = new ArrayList<String>(_list481.size);
          for (int _i482 = 0; _i482 < _list481.size; ++_i482)
          {
            String _elem483;
            _elem483 = iprot.readString();
            struct.last_query_phrase_seg.add(_elem483);
          }
        }
        struct.setLast_query_phrase_segIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list484 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.last_reply_basic_seg = new ArrayList<String>(_list484.size);
          for (int _i485 = 0; _i485 < _list484.size; ++_i485)
          {
            String _elem486;
            _elem486 = iprot.readString();
            struct.last_reply_basic_seg.add(_elem486);
          }
        }
        struct.setLast_reply_basic_segIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list487 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.last_reply_phrase_seg = new ArrayList<String>(_list487.size);
          for (int _i488 = 0; _i488 < _list487.size; ++_i488)
          {
            String _elem489;
            _elem489 = iprot.readString();
            struct.last_reply_phrase_seg.add(_elem489);
          }
        }
        struct.setLast_reply_phrase_segIsSet(true);
      }
    }
  }

}

