/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2018-7-28")
public class DebugInfo implements org.apache.thrift.TBase<DebugInfo, DebugInfo._Fields>, java.io.Serializable, Cloneable, Comparable<DebugInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DebugInfo");

  private static final org.apache.thrift.protocol.TField IS_DEBUG_FIELD_DESC = new org.apache.thrift.protocol.TField("is_debug", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField DEBUG_MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("debug_message", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DebugInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DebugInfoTupleSchemeFactory());
  }

  public boolean is_debug; // optional
  public String debug_message; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_DEBUG((short)1, "is_debug"),
    DEBUG_MESSAGE((short)2, "debug_message");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_DEBUG
          return IS_DEBUG;
        case 2: // DEBUG_MESSAGE
          return DEBUG_MESSAGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_DEBUG_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.IS_DEBUG,_Fields.DEBUG_MESSAGE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_DEBUG, new org.apache.thrift.meta_data.FieldMetaData("is_debug", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.DEBUG_MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("debug_message", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DebugInfo.class, metaDataMap);
  }

  public DebugInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DebugInfo(DebugInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.is_debug = other.is_debug;
    if (other.isSetDebug_message()) {
      this.debug_message = other.debug_message;
    }
  }

  public DebugInfo deepCopy() {
    return new DebugInfo(this);
  }

  
  public void clear() {
    setIs_debugIsSet(false);
    this.is_debug = false;
    this.debug_message = null;
  }

  public boolean isIs_debug() {
    return this.is_debug;
  }

  public DebugInfo setIs_debug(boolean is_debug) {
    this.is_debug = is_debug;
    setIs_debugIsSet(true);
    return this;
  }

  public void unsetIs_debug() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_DEBUG_ISSET_ID);
  }

  /** Returns true if field is_debug is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_debug() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_DEBUG_ISSET_ID);
  }

  public void setIs_debugIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_DEBUG_ISSET_ID, value);
  }

  public String getDebug_message() {
    return this.debug_message;
  }

  public DebugInfo setDebug_message(String debug_message) {
    this.debug_message = debug_message;
    return this;
  }

  public void unsetDebug_message() {
    this.debug_message = null;
  }

  /** Returns true if field debug_message is set (has been assigned a value) and false otherwise */
  public boolean isSetDebug_message() {
    return this.debug_message != null;
  }

  public void setDebug_messageIsSet(boolean value) {
    if (!value) {
      this.debug_message = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IS_DEBUG:
      if (value == null) {
        unsetIs_debug();
      } else {
        setIs_debug((Boolean)value);
      }
      break;

    case DEBUG_MESSAGE:
      if (value == null) {
        unsetDebug_message();
      } else {
        setDebug_message((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_DEBUG:
      return Boolean.valueOf(isIs_debug());

    case DEBUG_MESSAGE:
      return getDebug_message();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IS_DEBUG:
      return isSetIs_debug();
    case DEBUG_MESSAGE:
      return isSetDebug_message();
    }
    throw new IllegalStateException();
  }

  
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DebugInfo)
      return this.equals((DebugInfo)that);
    return false;
  }

  public boolean equals(DebugInfo that) {
    if (that == null)
      return false;

    boolean this_present_is_debug = true && this.isSetIs_debug();
    boolean that_present_is_debug = true && that.isSetIs_debug();
    if (this_present_is_debug || that_present_is_debug) {
      if (!(this_present_is_debug && that_present_is_debug))
        return false;
      if (this.is_debug != that.is_debug)
        return false;
    }

    boolean this_present_debug_message = true && this.isSetDebug_message();
    boolean that_present_debug_message = true && that.isSetDebug_message();
    if (this_present_debug_message || that_present_debug_message) {
      if (!(this_present_debug_message && that_present_debug_message))
        return false;
      if (!this.debug_message.equals(that.debug_message))
        return false;
    }

    return true;
  }

  
  public int hashCode() {
    return 0;
  }

  
  public int compareTo(DebugInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIs_debug()).compareTo(other.isSetIs_debug());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_debug()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_debug, other.is_debug);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDebug_message()).compareTo(other.isSetDebug_message());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDebug_message()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.debug_message, other.debug_message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  
  public String toString() {
    StringBuilder sb = new StringBuilder("DebugInfo(");
    boolean first = true;

    if (isSetIs_debug()) {
      sb.append("is_debug:");
      sb.append(this.is_debug);
      first = false;
    }
    if (isSetDebug_message()) {
      if (!first) sb.append(", ");
      sb.append("debug_message:");
      if (this.debug_message == null) {
        sb.append("null");
      } else {
        sb.append(this.debug_message);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DebugInfoStandardSchemeFactory implements SchemeFactory {
    public DebugInfoStandardScheme getScheme() {
      return new DebugInfoStandardScheme();
    }
  }

  private static class DebugInfoStandardScheme extends StandardScheme<DebugInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DebugInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_DEBUG
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_debug = iprot.readBool();
              struct.setIs_debugIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DEBUG_MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.debug_message = iprot.readString();
              struct.setDebug_messageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DebugInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetIs_debug()) {
        oprot.writeFieldBegin(IS_DEBUG_FIELD_DESC);
        oprot.writeBool(struct.is_debug);
        oprot.writeFieldEnd();
      }
      if (struct.debug_message != null) {
        if (struct.isSetDebug_message()) {
          oprot.writeFieldBegin(DEBUG_MESSAGE_FIELD_DESC);
          oprot.writeString(struct.debug_message);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DebugInfoTupleSchemeFactory implements SchemeFactory {
    public DebugInfoTupleScheme getScheme() {
      return new DebugInfoTupleScheme();
    }
  }

  private static class DebugInfoTupleScheme extends TupleScheme<DebugInfo> {

    
    public void write(org.apache.thrift.protocol.TProtocol prot, DebugInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIs_debug()) {
        optionals.set(0);
      }
      if (struct.isSetDebug_message()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetIs_debug()) {
        oprot.writeBool(struct.is_debug);
      }
      if (struct.isSetDebug_message()) {
        oprot.writeString(struct.debug_message);
      }
    }

    
    public void read(org.apache.thrift.protocol.TProtocol prot, DebugInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.is_debug = iprot.readBool();
        struct.setIs_debugIsSet(true);
      }
      if (incoming.get(1)) {
        struct.debug_message = iprot.readString();
        struct.setDebug_messageIsSet(true);
      }
    }
  }

}

