/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Domain implements org.apache.thrift.TEnum {
  UNKNOWN(0),
  CHAT(1),
  MUSIC(2),
  WEATHER(3),
  NEWS(4),
  CONTROL(5),
  REMIND(6),
  QA(7),
  JOKE(8),
  CALCULATOR(9),
  TIME(10),
  SYSPROFILE(11),
  SPORT_CONTROL(12),
  IOT_DEVICE_CONTROL(13),
  MOVIE_TICKET(14),
  TAKEOUT_FOOD(15),
  AUDIO_CHILD(16),
  AUDIO(17),
  KB(18),
  SHOPPING(19);

  private final int value;

  private Domain(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Domain findByValue(int value) { 
    switch (value) {
      case 0:
        return UNKNOWN;
      case 1:
        return CHAT;
      case 2:
        return MUSIC;
      case 3:
        return WEATHER;
      case 4:
        return NEWS;
      case 5:
        return CONTROL;
      case 6:
        return REMIND;
      case 7:
        return QA;
      case 8:
        return JOKE;
      case 9:
        return CALCULATOR;
      case 10:
        return TIME;
      case 11:
        return SYSPROFILE;
      case 12:
        return SPORT_CONTROL;
      case 13:
        return IOT_DEVICE_CONTROL;
      case 14:
        return MOVIE_TICKET;
      case 15:
        return TAKEOUT_FOOD;
      case 16:
        return AUDIO_CHILD;
      case 17:
        return AUDIO;
      case 18:
        return KB;
      case 19:
        return SHOPPING;
      default:
        return null;
    }
  }
}
