/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EventType implements org.apache.thrift.TEnum {
  UNKNOWN(0),
  ADD(1),
  DELETE(2),
  LIST(3),
  EXIT(4);

  private final int value;

  private EventType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EventType findByValue(int value) { 
    switch (value) {
      case 0:
        return UNKNOWN;
      case 1:
        return ADD;
      case 2:
        return DELETE;
      case 3:
        return LIST;
      case 4:
        return EXIT;
      default:
        return null;
    }
  }
}
