/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FanStatus implements org.apache.thrift.TEnum {
  UNKNOWN(0),
  TURN_ON(1),
  TURN_OFF(2),
  STATIC(3),
  SWING(4),
  SPEED_HI(5),
  SPEED_MID(6),
  SPEED_LOW(7),
  MODE_AUTO(8),
  MODE_SLEEP(9);

  private final int value;

  private FanStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FanStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return UNKNOWN;
      case 1:
        return TURN_ON;
      case 2:
        return TURN_OFF;
      case 3:
        return STATIC;
      case 4:
        return SWING;
      case 5:
        return SPEED_HI;
      case 6:
        return SPEED_MID;
      case 7:
        return SPEED_LOW;
      case 8:
        return MODE_AUTO;
      case 9:
        return MODE_SLEEP;
      default:
        return null;
    }
  }
}
