/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FrontendStatus implements org.apache.thrift.TEnum {
  IDLE(0),
  PLAYING(1),
  DANCING(2);

  private final int value;

  private FrontendStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FrontendStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return IDLE;
      case 1:
        return PLAYING;
      case 2:
        return DANCING;
      default:
        return null;
    }
  }
}
