/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProactiveTrigger implements org.apache.thrift.TEnum {
  EMPTY(0),
  STAR(1),
  VIDEO(2),
  TODAY_IN_HISTORY(3),
  SAY_HELLO(4);

  private final int value;

  private ProactiveTrigger(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProactiveTrigger findByValue(int value) { 
    switch (value) {
      case 0:
        return EMPTY;
      case 1:
        return STAR;
      case 2:
        return VIDEO;
      case 3:
        return TODAY_IN_HISTORY;
      case 4:
        return SAY_HELLO;
      default:
        return null;
    }
  }
}
