/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2018-7-28")
public class ReplyPornCondition implements org.apache.thrift.TBase<ReplyPornCondition, ReplyPornCondition._Fields>, java.io.Serializable, Cloneable, Comparable<ReplyPornCondition> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReplyPornCondition");

  private static final org.apache.thrift.protocol.TField IS_GBK_FIELD_DESC = new org.apache.thrift.protocol.TField("is_gbk", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField REMOVE_LETTER_FIELD_DESC = new org.apache.thrift.protocol.TField("remove_letter", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField FILTER_PORN_REPLY_IN_BRAIN_FIELD_DESC = new org.apache.thrift.protocol.TField("filter_porn_reply_in_brain", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReplyPornConditionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReplyPornConditionTupleSchemeFactory());
  }

  public boolean is_gbk; // optional
  public boolean remove_letter; // optional
  public boolean filter_porn_reply_in_brain; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_GBK((short)1, "is_gbk"),
    REMOVE_LETTER((short)3, "remove_letter"),
    FILTER_PORN_REPLY_IN_BRAIN((short)4, "filter_porn_reply_in_brain");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_GBK
          return IS_GBK;
        case 3: // REMOVE_LETTER
          return REMOVE_LETTER;
        case 4: // FILTER_PORN_REPLY_IN_BRAIN
          return FILTER_PORN_REPLY_IN_BRAIN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_GBK_ISSET_ID = 0;
  private static final int __REMOVE_LETTER_ISSET_ID = 1;
  private static final int __FILTER_PORN_REPLY_IN_BRAIN_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.IS_GBK,_Fields.REMOVE_LETTER,_Fields.FILTER_PORN_REPLY_IN_BRAIN};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_GBK, new org.apache.thrift.meta_data.FieldMetaData("is_gbk", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.REMOVE_LETTER, new org.apache.thrift.meta_data.FieldMetaData("remove_letter", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.FILTER_PORN_REPLY_IN_BRAIN, new org.apache.thrift.meta_data.FieldMetaData("filter_porn_reply_in_brain", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReplyPornCondition.class, metaDataMap);
  }

  public ReplyPornCondition() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReplyPornCondition(ReplyPornCondition other) {
    __isset_bitfield = other.__isset_bitfield;
    this.is_gbk = other.is_gbk;
    this.remove_letter = other.remove_letter;
    this.filter_porn_reply_in_brain = other.filter_porn_reply_in_brain;
  }

  public ReplyPornCondition deepCopy() {
    return new ReplyPornCondition(this);
  }

  
  public void clear() {
    setIs_gbkIsSet(false);
    this.is_gbk = false;
    setRemove_letterIsSet(false);
    this.remove_letter = false;
    setFilter_porn_reply_in_brainIsSet(false);
    this.filter_porn_reply_in_brain = false;
  }

  public boolean isIs_gbk() {
    return this.is_gbk;
  }

  public ReplyPornCondition setIs_gbk(boolean is_gbk) {
    this.is_gbk = is_gbk;
    setIs_gbkIsSet(true);
    return this;
  }

  public void unsetIs_gbk() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_GBK_ISSET_ID);
  }

  /** Returns true if field is_gbk is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_gbk() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_GBK_ISSET_ID);
  }

  public void setIs_gbkIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_GBK_ISSET_ID, value);
  }

  public boolean isRemove_letter() {
    return this.remove_letter;
  }

  public ReplyPornCondition setRemove_letter(boolean remove_letter) {
    this.remove_letter = remove_letter;
    setRemove_letterIsSet(true);
    return this;
  }

  public void unsetRemove_letter() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REMOVE_LETTER_ISSET_ID);
  }

  /** Returns true if field remove_letter is set (has been assigned a value) and false otherwise */
  public boolean isSetRemove_letter() {
    return EncodingUtils.testBit(__isset_bitfield, __REMOVE_LETTER_ISSET_ID);
  }

  public void setRemove_letterIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REMOVE_LETTER_ISSET_ID, value);
  }

  public boolean isFilter_porn_reply_in_brain() {
    return this.filter_porn_reply_in_brain;
  }

  public ReplyPornCondition setFilter_porn_reply_in_brain(boolean filter_porn_reply_in_brain) {
    this.filter_porn_reply_in_brain = filter_porn_reply_in_brain;
    setFilter_porn_reply_in_brainIsSet(true);
    return this;
  }

  public void unsetFilter_porn_reply_in_brain() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FILTER_PORN_REPLY_IN_BRAIN_ISSET_ID);
  }

  /** Returns true if field filter_porn_reply_in_brain is set (has been assigned a value) and false otherwise */
  public boolean isSetFilter_porn_reply_in_brain() {
    return EncodingUtils.testBit(__isset_bitfield, __FILTER_PORN_REPLY_IN_BRAIN_ISSET_ID);
  }

  public void setFilter_porn_reply_in_brainIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FILTER_PORN_REPLY_IN_BRAIN_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IS_GBK:
      if (value == null) {
        unsetIs_gbk();
      } else {
        setIs_gbk((Boolean)value);
      }
      break;

    case REMOVE_LETTER:
      if (value == null) {
        unsetRemove_letter();
      } else {
        setRemove_letter((Boolean)value);
      }
      break;

    case FILTER_PORN_REPLY_IN_BRAIN:
      if (value == null) {
        unsetFilter_porn_reply_in_brain();
      } else {
        setFilter_porn_reply_in_brain((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_GBK:
      return Boolean.valueOf(isIs_gbk());

    case REMOVE_LETTER:
      return Boolean.valueOf(isRemove_letter());

    case FILTER_PORN_REPLY_IN_BRAIN:
      return Boolean.valueOf(isFilter_porn_reply_in_brain());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IS_GBK:
      return isSetIs_gbk();
    case REMOVE_LETTER:
      return isSetRemove_letter();
    case FILTER_PORN_REPLY_IN_BRAIN:
      return isSetFilter_porn_reply_in_brain();
    }
    throw new IllegalStateException();
  }

  
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReplyPornCondition)
      return this.equals((ReplyPornCondition)that);
    return false;
  }

  public boolean equals(ReplyPornCondition that) {
    if (that == null)
      return false;

    boolean this_present_is_gbk = true && this.isSetIs_gbk();
    boolean that_present_is_gbk = true && that.isSetIs_gbk();
    if (this_present_is_gbk || that_present_is_gbk) {
      if (!(this_present_is_gbk && that_present_is_gbk))
        return false;
      if (this.is_gbk != that.is_gbk)
        return false;
    }

    boolean this_present_remove_letter = true && this.isSetRemove_letter();
    boolean that_present_remove_letter = true && that.isSetRemove_letter();
    if (this_present_remove_letter || that_present_remove_letter) {
      if (!(this_present_remove_letter && that_present_remove_letter))
        return false;
      if (this.remove_letter != that.remove_letter)
        return false;
    }

    boolean this_present_filter_porn_reply_in_brain = true && this.isSetFilter_porn_reply_in_brain();
    boolean that_present_filter_porn_reply_in_brain = true && that.isSetFilter_porn_reply_in_brain();
    if (this_present_filter_porn_reply_in_brain || that_present_filter_porn_reply_in_brain) {
      if (!(this_present_filter_porn_reply_in_brain && that_present_filter_porn_reply_in_brain))
        return false;
      if (this.filter_porn_reply_in_brain != that.filter_porn_reply_in_brain)
        return false;
    }

    return true;
  }

  
  public int hashCode() {
    return 0;
  }

  
  public int compareTo(ReplyPornCondition other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIs_gbk()).compareTo(other.isSetIs_gbk());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_gbk()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_gbk, other.is_gbk);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRemove_letter()).compareTo(other.isSetRemove_letter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRemove_letter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.remove_letter, other.remove_letter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFilter_porn_reply_in_brain()).compareTo(other.isSetFilter_porn_reply_in_brain());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFilter_porn_reply_in_brain()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.filter_porn_reply_in_brain, other.filter_porn_reply_in_brain);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  
  public String toString() {
    StringBuilder sb = new StringBuilder("ReplyPornCondition(");
    boolean first = true;

    if (isSetIs_gbk()) {
      sb.append("is_gbk:");
      sb.append(this.is_gbk);
      first = false;
    }
    if (isSetRemove_letter()) {
      if (!first) sb.append(", ");
      sb.append("remove_letter:");
      sb.append(this.remove_letter);
      first = false;
    }
    if (isSetFilter_porn_reply_in_brain()) {
      if (!first) sb.append(", ");
      sb.append("filter_porn_reply_in_brain:");
      sb.append(this.filter_porn_reply_in_brain);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReplyPornConditionStandardSchemeFactory implements SchemeFactory {
    public ReplyPornConditionStandardScheme getScheme() {
      return new ReplyPornConditionStandardScheme();
    }
  }

  private static class ReplyPornConditionStandardScheme extends StandardScheme<ReplyPornCondition> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReplyPornCondition struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_GBK
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_gbk = iprot.readBool();
              struct.setIs_gbkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REMOVE_LETTER
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.remove_letter = iprot.readBool();
              struct.setRemove_letterIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // FILTER_PORN_REPLY_IN_BRAIN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.filter_porn_reply_in_brain = iprot.readBool();
              struct.setFilter_porn_reply_in_brainIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReplyPornCondition struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetIs_gbk()) {
        oprot.writeFieldBegin(IS_GBK_FIELD_DESC);
        oprot.writeBool(struct.is_gbk);
        oprot.writeFieldEnd();
      }
      if (struct.isSetRemove_letter()) {
        oprot.writeFieldBegin(REMOVE_LETTER_FIELD_DESC);
        oprot.writeBool(struct.remove_letter);
        oprot.writeFieldEnd();
      }
      if (struct.isSetFilter_porn_reply_in_brain()) {
        oprot.writeFieldBegin(FILTER_PORN_REPLY_IN_BRAIN_FIELD_DESC);
        oprot.writeBool(struct.filter_porn_reply_in_brain);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReplyPornConditionTupleSchemeFactory implements SchemeFactory {
    public ReplyPornConditionTupleScheme getScheme() {
      return new ReplyPornConditionTupleScheme();
    }
  }

  private static class ReplyPornConditionTupleScheme extends TupleScheme<ReplyPornCondition> {

    
    public void write(org.apache.thrift.protocol.TProtocol prot, ReplyPornCondition struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIs_gbk()) {
        optionals.set(0);
      }
      if (struct.isSetRemove_letter()) {
        optionals.set(1);
      }
      if (struct.isSetFilter_porn_reply_in_brain()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetIs_gbk()) {
        oprot.writeBool(struct.is_gbk);
      }
      if (struct.isSetRemove_letter()) {
        oprot.writeBool(struct.remove_letter);
      }
      if (struct.isSetFilter_porn_reply_in_brain()) {
        oprot.writeBool(struct.filter_porn_reply_in_brain);
      }
    }

    
    public void read(org.apache.thrift.protocol.TProtocol prot, ReplyPornCondition struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.is_gbk = iprot.readBool();
        struct.setIs_gbkIsSet(true);
      }
      if (incoming.get(1)) {
        struct.remove_letter = iprot.readBool();
        struct.setRemove_letterIsSet(true);
      }
      if (incoming.get(2)) {
        struct.filter_porn_reply_in_brain = iprot.readBool();
        struct.setFilter_porn_reply_in_brainIsSet(true);
      }
    }
  }

}

