/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ServiceName implements org.apache.thrift.TEnum {
  BRAIN(0),
  CHAT(1),
  SINGLEROUND(2),
  QUERYPOST(3),
  QUERYREPLY(4),
  VERTICAL(5),
  JOKE(6),
  NEWS(7),
  WEATHER(8),
  SYSPROFILE(9),
  QA(10),
  TCD(11),
  KB(12),
  FAQ(13),
  SNEWS(14),
  CALCULATOR(15),
  TIME(16),
  FAQAPI(17),
  GENERATIVECHAT(18),
  WORKFLOW(19),
  CHAT_FOXCONN(20),
  CONTROL(21),
  SPORT_CONTROL(22),
  IOT_DEVICE_CONTROL(23),
  REMIND(24),
  MUSIC(25),
  SKILL_TEST_BRAIN(26),
  MOVIE_TICKET(27),
  TAKEOUT_FOOD(28),
  AUDIO_CHILD(29),
  AUDIO(30),
  SHOPPING(31);

  private final int value;

  private ServiceName(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServiceName findByValue(int value) { 
    switch (value) {
      case 0:
        return BRAIN;
      case 1:
        return CHAT;
      case 2:
        return SINGLEROUND;
      case 3:
        return QUERYPOST;
      case 4:
        return QUERYREPLY;
      case 5:
        return VERTICAL;
      case 6:
        return JOKE;
      case 7:
        return NEWS;
      case 8:
        return WEATHER;
      case 9:
        return SYSPROFILE;
      case 10:
        return QA;
      case 11:
        return TCD;
      case 12:
        return KB;
      case 13:
        return FAQ;
      case 14:
        return SNEWS;
      case 15:
        return CALCULATOR;
      case 16:
        return TIME;
      case 17:
        return FAQAPI;
      case 18:
        return GENERATIVECHAT;
      case 19:
        return WORKFLOW;
      case 20:
        return CHAT_FOXCONN;
      case 21:
        return CONTROL;
      case 22:
        return SPORT_CONTROL;
      case 23:
        return IOT_DEVICE_CONTROL;
      case 24:
        return REMIND;
      case 25:
        return MUSIC;
      case 26:
        return SKILL_TEST_BRAIN;
      case 27:
        return MOVIE_TICKET;
      case 28:
        return TAKEOUT_FOOD;
      case 29:
        return AUDIO_CHILD;
      case 30:
        return AUDIO;
      case 31:
        return SHOPPING;
      default:
        return null;
    }
  }
}
